### PR TITLE
Added improved IP validation for port mapper

### PR DESCRIPTION
**Pull request by bboehmke**
This should fix moby/moby#41699

### CODE REVIEW

**Comment by arkodg** [comment]
looks like there are multiple instances where the check is needed
1.https://github.com/moby/libnetwork/blob/535ef365dc1dd82a5135803a58bc6198a3b9aa27/portmapper/mapper.go#L229
2.https://github.com/moby/libnetwork/blob/535ef365dc1dd82a5135803a58bc6198a3b9aa27/portmapper/mapper.go#L203

It might be simpler to keep the code scoped within https://github.com/moby/libnetwork/blob/master/portmapper/mapper_linux.go
and perform the check in `AppendForwardingTableEntry` and `DeleteForwardingTableEntry` to make sure the Host IP, Container IP and `chain.IPTable.Version` are all the same version (either IPv4 or IPv6) and if not we should skip the `forward` call and print a Warning (ideally its an error but we need to support backward compatibility)

**Comment by bboehmke** [comment]
I have already thought about it but there is also a call to `pm.Allocator.ReleasePort()` that is covered by this check so it is not enough to catch the `forward` call in the port mapper.

I think the cleanest way is maybe to call the `MapRange` function only for the right protocol version. But here I am not sure if this causes some other issues because the function does a lot of thinks (which I not fully understand).

**Comment by arkodg** [comment]
I see your point, we'll still end up reserving the port even if we don't use it, which is not the right thing to do

**Review by tiborvass — APPROVED** [review]
This seems to work, so let's take this for rc2. If there are followup refactors or places where we think such a check is needed, feel free to add them.

**Pull request merged**
