### PR TITLE
Only check if route overlaps routes with scope: LINK

### PR DESCRIPTION
**Pull request by Nossnevs**
Signed-off-by: Mikael Svensson <mikael.svensson@nasdaq.com>

PR for completing https://github.com/moby/moby/pull/43360 to backbort fix from https://github.com/moby/moby/pull/42598 to moby 20.10
Update to https://github.com/moby/moby/pull/43360  will happen when this is merged.

### CODE REVIEW

**Comment by Nossnevs** [comment]
The failing test does not seam to be related to this PR.

**Comment by Nossnevs** [comment]
@thaJeztah i see that other PR have some problems also with the CI. Do you think we can get this PR in without change the CI pipeline?

**Comment by thaJeztah** [comment]
I kicked CI again, and it's green now, so looks like just a flaky test 👍

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

compared the diff with https://github.com/moby/moby/pull/42598, and they're identical

**Pull request merged**
