### PR TITLE
netfilter's ipset, initial coding

### PR DESCRIPTION
**Pull request by Pirabarlen-Cheenaramen**
Work in progress.

### CODE REVIEW

**Comment by chenchun** [comment]
@Pirabarlen-Cheenaramen You can always rebase againt master instead of creating a new PR as the robot @GordonTheTurtle said.

**Comment by Pirabarlen-Cheenaramen** [comment]
@chenchun , thanks, so, I can just set all list of commits as edit, even if they are not mine, and do the amend then? 

Thanks, been a bit confused with the rebasing.

**Comment by Pirabarlen-Cheenaramen** [comment]
@chenchun , will do that. thanks.

**Comment by Pirabarlen-Cheenaramen** [comment]
still in progress.

**Comment by akerouanton** [comment]
Thanks @Pirabarlen-Cheenaramen for your work. I'll close this PR for the following reasons:

1. This repo has been moved to https://github.com/moby/moby/tree/master/libnetwork. Any new work should happen there, and backported in this repo iff required ;
2. It's unfinished and hasn't seen any activity in the past 7 years.

**Pull request closed without merging**
