### PR TITLE
Add RemoteAPI implementation

### PR DESCRIPTION
**Pull request by eyakubovich**
- Add an implemenation of Controller and related
  interfaces that makes REST calls to the API endpoint.
- Add a new API endpoint to get endpoint info

Signed-off-by: Eugene Yakubovich eugene.yakubovich@coreos.com

### CODE REVIEW

**Comment by eyakubovich** [comment]
This is currently slightly outdated but I can fix it up if the general direction is fine. Looking for initial feedback.

**Comment by mavenugo** [comment]
@eyakubovich Apologies on the delay. Overall approach LGTM. There has been a few changes in the data-structures recently and more coming via #429. But, we can get this merged if you can rebase to the latest and appropriate tests.

**Comment by eyakubovich** [comment]
I will give rebase shortly.

**Comment by aboch** [comment]
@eyakubovich Was wondering whether these new files should go inside a separate client package. At the end this is a libnetwork rest client implementation, I feel it should not reside along with the server api files.

**Comment by eyakubovich** [comment]
@aboch I can put it into a separate package. I was going off that the `api` package is all about remote API. Kind of like standard `net/http` package has both client and server code.

**Comment by aboch** [comment]
Thanks @eyakubovich, net/http is a good reference for this.

**Comment by eyakubovich** [comment]
There are some methods that return `ErrNotImplemented` or `panic`. If it makes sense, I can try to add the required functionality to the remote API and then implement them.

**Comment by aboch** [comment]
Thanks @eyakubovich, I think it makes sense to complete the client api.
I am not  sure about ConfigureDriver(), for sure avoid to implement LeaveAll() as it is being removed (see #365).

**Pull request closed without merging**
