### PR TITLE
Make sure IPv6 is enabled for IP6tables

### PR DESCRIPTION
**Pull request by arkodg**
Signed-off-by: Arko Dasgupta <arko.dasgupta@docker.com>

Relates to https://github.com/moby/moby/issues/41774

### CODE REVIEW

**Comment by arkodg** [comment]
cc @bboehmke

**Comment by bboehmke** [comment]
This seems to fix the crash but I think it would also make sense to add the same to
```go
{d.config.EnableIP6Tables, network.setupFirewalld6},
```
some lines below.

**Comment by arkodg** [comment]
hey @bboehmke if this LGTY, can you please approve the PR :), TIA

**Comment by bboehmke** [comment]
LGTM for me

**Review by tiborvass — APPROVED** [review]

**Pull request merged**
