### PR TITLE
fixes issue 24043: container communication is open even when dockerd is started with --icc=false.

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Fixes https://github.com/docker/docker/issues/24043 

Signed-off-by: Shishir Mahajan shishir.mahajan@redhat.com

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
ping @cpuguy83

**Comment by thaJeztah** [comment]
ping @cpuguy83 PTAL

**Comment by rhatdan** [comment]
Any movement on this one?

**Comment by thaJeztah** [comment]
ping @mrjana @sanimej PTAL

**Comment by shishir-a412ed** [comment]
Any updates on this one ?

**Comment by thaJeztah** [comment]
ping @mrjana @sanimej PTAL

**Comment by thaJeztah** [comment]
closing, per https://github.com/moby/moby/issues/24043#issuecomment-1976230402, but /cc @akerouanton in case there's parts of this that we'd still need in moby

**Pull request closed without merging**
