### PR TITLE
Use vendored ipvs package

### PR DESCRIPTION
**Pull request by cpuguy83**
The ipvs package was moved to a separate repo.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Hm.. looks like some networking issues in CI

```
Step 2/8 : FROM golang:${GO_VERSION}-buster as dev
1.13.8-buster: Pulling from library/golang

31f79093: Pulling fs layer 
6d374ea5: Pulling fs layer 
13200d84: Pulling fs layer 
9680e827: Pulling fs layer 
7f5e50c4: Pulling fs layer 
b328fba5: Pulling fs layer 
make: *** [Makefile:39: builder] Terminated

Too long with no output (exceeded 10m0s): context deadline exceeded
```

**Comment by thaJeztah** [comment]
kicked it again

**Comment by cpuguy83** [comment]
Tests are green.

**Comment by arkodg** [comment]
@cpuguy83 can you please update the commit message linking it to the relevant issue and stating the need to do this - not having to vendor in the entire `libnetwork` or `moby`
thanks !

**Comment by cpuguy83** [comment]
Updated the commit message.

**Pull request merged**
